<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>firstLineMatch</key>
	<string>^\;(?:[ \t]+)(?:.*)$</string>
	<key>foldingStartMarker</key>
	<string>define_(task|subroutine|verb)|\{\{\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>end_(task|subroutine|verb)|\s*\}\}\}</string>
	<key>name</key>
	<string>Hourglass</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.hourglass</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\;\s*(.*)</string>
			<key>name</key>
			<string>comment.line.first-line.hourglass</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.hourglass</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*\;\s*(.*)$</string>
			<key>name</key>
			<string>comment.line.inline.hourglass</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.define.hourglass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.hourglass</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(define_(?:subroutine|task|label|verb))\"([^"]+)\"\s*$</string>
			<key>name</key>
			<string>meta.function.hourglass</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jump.hourglass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.hourglass</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(goto|gosub|\!)\"([^"]+)\"</string>
			<key>name</key>
			<string>meta.jump.hourglass</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.hourglass</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\#[A-Z]+)\b</string>
			<key>name</key>
			<string>constant.hourglass</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.hourglass</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\$[[:alnum:]]+\b</string>
			<key>name</key>
			<string>variable.other.string.hourglass</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(while|if|then|return|out_\w+|end_\w+)\b(?![?!])</string>
			<key>name</key>
			<string>keyword.control.hourglass</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hourglass</string>
	<key>uuid</key>
	<string>A2E93B0D-F212-402A-A347-52A0BF492A6B</string>
</dict>
</plist>
